# Generated by Django 4.2.9 on 2024-01-12 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('validator', models.CharField(max_length=50)),
                ('example', models.CharField(max_length=50)),
                ('allowed_cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.card')),
            ],
        ),
    ]
