# Generated by Django 4.2.9 on 2024-01-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='allowed_cards',
        ),
        migrations.AddField(
            model_name='card',
            name='allowed_cards',
            field=models.ManyToManyField(blank=True, null=True, related_name='cards_for_payment', to='transactions.card'),
        ),
    ]
